version: '2'
services:
    tutojhipster-app:
        image: tutojhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tutojhipster-mysql:3306/tutojhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tutojhipster-elasticsearch:9300
        ports:
            - 8080:8080
    tutojhipster-mysql:
        extends:
            file: mysql.yml
            service: tutojhipster-mysql
    tutojhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tutojhipster-elasticsearch
